[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/contracts/",
  "@openzeppelin-contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@solady/=node_modules/solady/src/"
]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
